// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NovaStay.Infrastructure.ContextDB;

#nullable disable

namespace NovaStay.Infrastructure.Migrations
{
    [DbContext(typeof(HostContext))]
    partial class HostContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NovaStay.Infrastructure.Models.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<string>("AccountType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime");

                    b.Property<bool?>("MustSetPassword")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("PasswordSetAt")
                        .HasColumnType("datetime");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.HasKey("Id")
                        .HasName("PK_Accounts");

                    b.HasIndex(new[] { "Email" }, "IX_Accounts_Email");

                    b.HasIndex(new[] { "Phone" }, "IX_Accounts_Phone")
                        .IsUnique();

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("NovaStay.Infrastructure.Models.AccountRefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("CreatedByIp")
                        .HasMaxLength(45)
                        .IsUnicode(false)
                        .HasColumnType("varchar(45)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime");

                    b.Property<string>("ReplacedByTokenHash")
                        .HasMaxLength(512)
                        .IsUnicode(false)
                        .HasColumnType("varchar(512)");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("RevokedByIp")
                        .HasMaxLength(45)
                        .IsUnicode(false)
                        .HasColumnType("varchar(45)");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .IsUnicode(false)
                        .HasColumnType("varchar(512)");

                    b.HasKey("Id")
                        .HasName("PK_AccountRefreshTokens");

                    b.HasIndex(new[] { "AccountId", "ExpiresAt" }, "IX_AccountRefreshTokens_AccountId_ExpiresAt");

                    b.HasIndex(new[] { "TokenHash" }, "IX_AccountRefreshTokens_TokenHash")
                        .IsUnique();

                    b.ToTable("AccountRefreshTokens");
                });

            modelBuilder.Entity("NovaStay.Infrastructure.Models.Asset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<string>("AssetCode")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("AssetName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("BaseValue")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 2)")
                        .HasDefaultValue(0m);

                    b.Property<string>("Brand")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Category")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Model")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly?>("PurchaseDate")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("WarrantyExpiryDate")
                        .HasColumnType("date");

                    b.HasKey("Id")
                        .HasName("PK__Assets__3214EC071B1A8B14");

                    b.HasIndex("OrganizationId");

                    b.ToTable("Assets");
                });

            modelBuilder.Entity("NovaStay.Infrastructure.Models.AssetAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("AssignedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Note")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("RoomId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("Good");

                    b.HasKey("Id")
                        .HasName("PK__AssetAss__3214EC073B842B58");

                    b.HasIndex("AssetId");

                    b.HasIndex("OrganizationId");

                    b.HasIndex(new[] { "RoomId" }, "IX_AssetAssignments_RoomId");

                    b.ToTable("AssetAssignments");
                });

            modelBuilder.Entity("NovaStay.Infrastructure.Models.Booking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("BookingType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<DateOnly>("CheckInDate")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("CheckOutDate")
                        .HasColumnType("date");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("GuestEmail")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("GuestName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("GuestPhone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PaymentStatus")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("Pending");

                    b.Property<string>("PaymentTransactionId")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK__Bookings__3214EC07E0378A72");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("PropertyId");

                    b.HasIndex("RoomId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("NovaStay.Infrastructure.Models.Broker", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.Property<decimal?>("TotalCommissionEarned")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 2)")
                        .HasDefaultValue(0m);

                    b.Property<decimal?>("WalletBalance")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 2)")
                        .HasDefaultValue(0m);

                    b.HasKey("Id")
                        .HasName("PK__Brokers__3214EC07D3AA9FC2");

                    b.HasIndex("OrganizationId");

                    b.ToTable("Brokers");
                });

            modelBuilder.Entity("NovaStay.Infrastructure.Models.Contract", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<Guid?>("BookingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("BrokerCommission")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 2)")
                        .HasDefaultValue(0m);

                    b.Property<Guid?>("BrokerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CommissionStatus")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("Pending");

                    b.Property<string>("ContractPdfUrl")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<decimal>("DepositAmount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ResidentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id")
                        .HasName("PK__Contract__3214EC0707402DA0");

                    b.HasIndex("BookingId");

                    b.HasIndex("BrokerId");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("PropertyId");

                    b.HasIndex("ResidentId");

                    b.HasIndex("RoomId");

                    b.ToTable("Contracts");
                });

            modelBuilder.Entity("NovaStay.Infrastructure.Models.Invoice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<Guid?>("BookingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ContractId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("InvoicePeriod")
                        .IsRequired()
                        .HasMaxLength(7)
                        .IsUnicode(false)
                        .HasColumnType("varchar(7)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("datetime");

                    b.Property<string>("QrCodeUrl")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<decimal>("RoomPrice")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("ServicesPrice")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("Unpaid");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("Id")
                        .HasName("PK__Invoices__3214EC07023BFFC1");

                    b.HasIndex("BookingId");

                    b.HasIndex("ContractId");

                    b.HasIndex("OrganizationId");

                    b.HasIndex(new[] { "Status", "InvoicePeriod" }, "IX_Invoices_Status_Period");

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("NovaStay.Infrastructure.Models.MaintenanceTicket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<Guid?>("AssetAssignmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("IncidentImageUrl")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ResidentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ResolvedImageUrl")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("Pending");

                    b.Property<Guid?>("TechnicianId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("UserDescription")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id")
                        .HasName("PK__Maintena__3214EC071D5966C6");

                    b.HasIndex("AssetAssignmentId");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("ResidentId");

                    b.HasIndex("RoomId");

                    b.HasIndex("TechnicianId");

                    b.ToTable("MaintenanceTickets");
                });

            modelBuilder.Entity("NovaStay.Infrastructure.Models.Organization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<string>("BusinessArea")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("BusinessName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<Guid>("OwnerAccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("OwnerEmail")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("OwnerPhone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.Property<Guid>("PackageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SubscriptionStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("TaxCode")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<int?>("TokenBalance")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime");

                    b.HasKey("Id")
                        .HasName("PK__Organizations__3214EC070623D35C");

                    b.HasIndex(new[] { "OwnerAccountId" }, "IX_Organizations_OwnerAccountId");

                    b.HasIndex(new[] { "PackageId" }, "IX_Organizations_PackageId");

                    b.HasIndex(new[] { "OwnerEmail" }, "UQ__Organizations__FF0186BBAE6B6868")
                        .IsUnique();

                    b.ToTable("Organizations");
                });

            modelBuilder.Entity("NovaStay.Infrastructure.Models.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<string>("Module")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("PermissionKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("PermissionName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id")
                        .HasName("PK__Permissi__3214EC0720D981B2");

                    b.HasIndex(new[] { "PermissionKey" }, "UQ__Permissi__8884ABD46702546C")
                        .IsUnique();

                    b.ToTable("Permissions");
                });

            modelBuilder.Entity("NovaStay.Infrastructure.Models.Property", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PropertyName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("PropertyType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id")
                        .HasName("PK__Properti__3214EC07FE441D45");

                    b.HasIndex("OrganizationId");

                    b.ToTable("Properties");
                });

            modelBuilder.Entity("NovaStay.Infrastructure.Models.PropertyService", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<string>("BillingCycle")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<decimal>("DefaultPrice")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ServiceCode")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("ServiceName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Unit")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime");

                    b.HasKey("Id")
                        .HasName("PK_PropertyServices");

                    b.HasIndex(new[] { "PropertyId", "IsActive" }, "IX_PropertyServices_PropertyId_IsActive");

                    b.HasIndex(new[] { "PropertyId", "ServiceName" }, "UX_PropertyServices_PropertyId_ServiceName")
                        .IsUnique();

                    b.ToTable("PropertyServices");
                });

            modelBuilder.Entity("NovaStay.Infrastructure.Models.Resident", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("IdBackImageUrl")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("IdFrontImageUrl")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("IdentityCardNumber")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.Property<string>("ProfileImageUrl")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Sex")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id")
                        .HasName("PK__Resident__3214EC07115F9503");

                    b.HasIndex(new[] { "AccountId" }, "IX_Residents_AccountId")
                        .IsUnique();

                    b.ToTable("Residents");
                });

            modelBuilder.Entity("NovaStay.Infrastructure.Models.ResidentMembership", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ActivatedAt")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("InvitedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("JoinedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("MembershipCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ResidentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("RespondedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("Pending");

                    b.HasKey("Id")
                        .HasName("PK_ResidentMemberships");

                    b.HasIndex(new[] { "AccountId" }, "IX_ResidentMemberships_AccountId");

                    b.HasIndex(new[] { "OrganizationId" }, "IX_ResidentMemberships_OrganizationId");

                    b.HasIndex(new[] { "ResidentId" }, "IX_ResidentMemberships_ResidentId");

                    b.HasIndex(new[] { "AccountId", "OrganizationId" }, "UX_ResidentMemberships_AccountId_OrganizationId")
                        .IsUnique();

                    b.HasIndex(new[] { "MembershipCode" }, "UX_ResidentMemberships_MembershipCode")
                        .IsUnique();

                    b.ToTable("ResidentMemberships");
                });

            modelBuilder.Entity("NovaStay.Infrastructure.Models.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RoleKey")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK__Roles__3214EC07BE72DF6E");

                    b.HasIndex("OrganizationId");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("NovaStay.Infrastructure.Models.Room", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<string>("AmenitiesJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("BasePrice")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("Floor")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int?>("MaxOccupants")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RoomNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id")
                        .HasName("PK__Rooms__3214EC077FA99C97");

                    b.HasIndex(new[] { "PropertyId", "Status" }, "IX_Rooms_PropertyId_Status");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("NovaStay.Infrastructure.Models.RoomAvailability", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<decimal>("DynamicPrice")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<bool?>("IsBooked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("StayDate")
                        .HasColumnType("date");

                    b.HasKey("Id")
                        .HasName("PK__RoomAvai__3214EC07207FCE01");

                    b.HasIndex("RoomId");

                    b.ToTable("RoomAvailabilities");
                });

            modelBuilder.Entity("NovaStay.Infrastructure.Models.RoomImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<bool?>("IsCover")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UploadedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("Id")
                        .HasName("PK__RoomImag__3214EC079F9973C0");

                    b.HasIndex(new[] { "RoomId" }, "IX_RoomImages_RoomId");

                    b.ToTable("RoomImages");
                });

            modelBuilder.Entity("NovaStay.Infrastructure.Models.RoomService", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<DateTime?>("AssignedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Note")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal?>("PriceOverride")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<Guid>("PropertyServiceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("RemovedAt")
                        .HasColumnType("datetime");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK_RoomServices");

                    b.HasIndex(new[] { "PropertyServiceId" }, "IX_RoomServices_PropertyServiceId");

                    b.HasIndex(new[] { "RoomId" }, "IX_RoomServices_RoomId");

                    b.HasIndex(new[] { "RoomId", "PropertyServiceId" }, "UX_RoomServices_RoomId_PropertyServiceId")
                        .IsUnique();

                    b.ToTable("RoomServices");
                });

            modelBuilder.Entity("NovaStay.Infrastructure.Models.StaffUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK__Users__3214EC078909D83A");

                    b.HasIndex(new[] { "AccountId" }, "IX_StaffUsers_AccountId")
                        .IsUnique();

                    b.HasIndex(new[] { "OrganizationId" }, "IX_Users_OrganizationId");

                    b.ToTable("StaffUsers");
                });

            modelBuilder.Entity("NovaStay.Infrastructure.Models.SubscriptionPackage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<bool?>("AllowAiFeatures")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool?>("AllowCustomRoles")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("MaxProperties")
                        .HasColumnType("int");

                    b.Property<int>("MaxRooms")
                        .HasColumnType("int");

                    b.Property<string>("PackageKey")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("PackageName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("PriceMonthly")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int?>("TokenGiftMonthly")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("Id")
                        .HasName("PK__Subscrip__3214EC077D1660D7");

                    b.HasIndex(new[] { "PackageKey" }, "UQ__Subscrip__63953E72B6E7DAB9")
                        .IsUnique();

                    b.ToTable("SubscriptionPackages");
                });

            modelBuilder.Entity("NovaStay.Infrastructure.Models.Technician", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool?>("IsAvailable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.Property<string>("Specialty")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK__Technici__3214EC0701E593D1");

                    b.HasIndex("OrganizationId");

                    b.ToTable("Technicians");
                });

            modelBuilder.Entity("RolePermission", b =>
                {
                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("RoleId", "PermissionId")
                        .HasName("PK__RolePerm__6400A1A8CB2E4434");

                    b.HasIndex("PermissionId");

                    b.ToTable("RolePermissions", (string)null);
                });

            modelBuilder.Entity("StaffUserPropertyMapping", b =>
                {
                    b.Property<Guid>("StaffUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("StaffUserId", "PropertyId")
                        .HasName("PK__UserProp__5084563FC247FEEC");

                    b.HasIndex("PropertyId");

                    b.ToTable("StaffUserPropertyMapping", (string)null);
                });

            modelBuilder.Entity("StaffUserRole", b =>
                {
                    b.Property<Guid>("StaffUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("StaffUserId", "RoleId")
                        .HasName("PK__UserRole__AF2760AD29238DE0");

                    b.HasIndex("RoleId");

                    b.ToTable("StaffUserRoles", (string)null);
                });

            modelBuilder.Entity("NovaStay.Infrastructure.Models.AccountRefreshToken", b =>
                {
                    b.HasOne("NovaStay.Infrastructure.Models.Account", "Account")
                        .WithMany("AccountRefreshTokens")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_AccountRefreshTokens_Accounts_AccountId");

                    b.Navigation("Account");
                });

            modelBuilder.Entity("NovaStay.Infrastructure.Models.Asset", b =>
                {
                    b.HasOne("NovaStay.Infrastructure.Models.Organization", "Organization")
                        .WithMany("Assets")
                        .HasForeignKey("OrganizationId")
                        .IsRequired()
                        .HasConstraintName("FK__Assets__OrganizationId__02FC7413");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("NovaStay.Infrastructure.Models.AssetAssignment", b =>
                {
                    b.HasOne("NovaStay.Infrastructure.Models.Asset", "Asset")
                        .WithMany("AssetAssignments")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__AssetAssi__Asset__08B54D69");

                    b.HasOne("NovaStay.Infrastructure.Models.Organization", "Organization")
                        .WithMany("AssetAssignments")
                        .HasForeignKey("OrganizationId")
                        .IsRequired()
                        .HasConstraintName("FK__AssetAssi__Tenan__07C12930");

                    b.HasOne("NovaStay.Infrastructure.Models.Room", "Room")
                        .WithMany("AssetAssignments")
                        .HasForeignKey("RoomId")
                        .HasConstraintName("FK__AssetAssi__RoomI__09A971A2");

                    b.Navigation("Asset");

                    b.Navigation("Organization");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("NovaStay.Infrastructure.Models.Booking", b =>
                {
                    b.HasOne("NovaStay.Infrastructure.Models.Organization", "Organization")
                        .WithMany("Bookings")
                        .HasForeignKey("OrganizationId")
                        .IsRequired()
                        .HasConstraintName("FK__Bookings__Organization__1BC821DD");

                    b.HasOne("NovaStay.Infrastructure.Models.Property", "Property")
                        .WithMany("Bookings")
                        .HasForeignKey("PropertyId")
                        .IsRequired()
                        .HasConstraintName("FK__Bookings__Proper__1CBC4616");

                    b.HasOne("NovaStay.Infrastructure.Models.Room", "Room")
                        .WithMany("Bookings")
                        .HasForeignKey("RoomId")
                        .IsRequired()
                        .HasConstraintName("FK__Bookings__RoomId__1DB06A4F");

                    b.Navigation("Organization");

                    b.Navigation("Property");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("NovaStay.Infrastructure.Models.Broker", b =>
                {
                    b.HasOne("NovaStay.Infrastructure.Models.Organization", "Organization")
                        .WithMany("Brokers")
                        .HasForeignKey("OrganizationId")
                        .IsRequired()
                        .HasConstraintName("FK__Brokers__OrganizationI__2739D489");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("NovaStay.Infrastructure.Models.Contract", b =>
                {
                    b.HasOne("NovaStay.Infrastructure.Models.Booking", "Booking")
                        .WithMany("Contracts")
                        .HasForeignKey("BookingId")
                        .HasConstraintName("FK__Contracts__Booki__32AB8735");

                    b.HasOne("NovaStay.Infrastructure.Models.Broker", "Broker")
                        .WithMany("Contracts")
                        .HasForeignKey("BrokerId")
                        .HasConstraintName("FK__Contracts__Broke__31B762FC");

                    b.HasOne("NovaStay.Infrastructure.Models.Organization", "Organization")
                        .WithMany("Contracts")
                        .HasForeignKey("OrganizationId")
                        .IsRequired()
                        .HasConstraintName("FK__Contracts__Tenan__2CF2ADDF");

                    b.HasOne("NovaStay.Infrastructure.Models.Property", "Property")
                        .WithMany("Contracts")
                        .HasForeignKey("PropertyId")
                        .IsRequired()
                        .HasConstraintName("FK__Contracts__Prope__2DE6D218");

                    b.HasOne("NovaStay.Infrastructure.Models.Resident", "Resident")
                        .WithMany("Contracts")
                        .HasForeignKey("ResidentId")
                        .IsRequired()
                        .HasConstraintName("FK__Contracts__Resid__30C33EC3");

                    b.HasOne("NovaStay.Infrastructure.Models.Room", "Room")
                        .WithMany("Contracts")
                        .HasForeignKey("RoomId")
                        .IsRequired()
                        .HasConstraintName("FK__Contracts__RoomI__2EDAF651");

                    b.Navigation("Booking");

                    b.Navigation("Broker");

                    b.Navigation("Organization");

                    b.Navigation("Property");

                    b.Navigation("Resident");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("NovaStay.Infrastructure.Models.Invoice", b =>
                {
                    b.HasOne("NovaStay.Infrastructure.Models.Booking", "Booking")
                        .WithMany("Invoices")
                        .HasForeignKey("BookingId")
                        .HasConstraintName("FK__Invoices__Bookin__395884C4");

                    b.HasOne("NovaStay.Infrastructure.Models.Contract", "Contract")
                        .WithMany("Invoices")
                        .HasForeignKey("ContractId")
                        .HasConstraintName("FK__Invoices__Contra__3864608B");

                    b.HasOne("NovaStay.Infrastructure.Models.Organization", "Organization")
                        .WithMany("Invoices")
                        .HasForeignKey("OrganizationId")
                        .IsRequired()
                        .HasConstraintName("FK__Invoices__Organization__37703C52");

                    b.Navigation("Booking");

                    b.Navigation("Contract");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("NovaStay.Infrastructure.Models.MaintenanceTicket", b =>
                {
                    b.HasOne("NovaStay.Infrastructure.Models.AssetAssignment", "AssetAssignment")
                        .WithMany("MaintenanceTickets")
                        .HasForeignKey("AssetAssignmentId")
                        .HasConstraintName("FK__Maintenan__Asset__44CA3770");

                    b.HasOne("NovaStay.Infrastructure.Models.Organization", "Organization")
                        .WithMany("MaintenanceTickets")
                        .HasForeignKey("OrganizationId")
                        .IsRequired()
                        .HasConstraintName("FK__Maintenan__Tenan__41EDCAC5");

                    b.HasOne("NovaStay.Infrastructure.Models.Resident", "Resident")
                        .WithMany("MaintenanceTickets")
                        .HasForeignKey("ResidentId")
                        .HasConstraintName("FK__Maintenan__Resid__43D61337");

                    b.HasOne("NovaStay.Infrastructure.Models.Room", "Room")
                        .WithMany("MaintenanceTickets")
                        .HasForeignKey("RoomId")
                        .IsRequired()
                        .HasConstraintName("FK__Maintenan__RoomI__42E1EEFE");

                    b.HasOne("NovaStay.Infrastructure.Models.Technician", "Technician")
                        .WithMany("MaintenanceTickets")
                        .HasForeignKey("TechnicianId")
                        .HasConstraintName("FK__Maintenan__Techn__45BE5BA9");

                    b.Navigation("AssetAssignment");

                    b.Navigation("Organization");

                    b.Navigation("Resident");

                    b.Navigation("Room");

                    b.Navigation("Technician");
                });

            modelBuilder.Entity("NovaStay.Infrastructure.Models.Organization", b =>
                {
                    b.HasOne("NovaStay.Infrastructure.Models.Account", "OwnerAccount")
                        .WithMany("OwnedOrganizations")
                        .HasForeignKey("OwnerAccountId")
                        .IsRequired()
                        .HasConstraintName("FK_Organizations_Accounts_OwnerAccountId");

                    b.HasOne("NovaStay.Infrastructure.Models.SubscriptionPackage", "Package")
                        .WithMany("Organizations")
                        .HasForeignKey("PackageId")
                        .IsRequired()
                        .HasConstraintName("FK__Organizations__Package__534D60F1");

                    b.Navigation("OwnerAccount");

                    b.Navigation("Package");
                });

            modelBuilder.Entity("NovaStay.Infrastructure.Models.Property", b =>
                {
                    b.HasOne("NovaStay.Infrastructure.Models.Organization", "Organization")
                        .WithMany("Properties")
                        .HasForeignKey("OrganizationId")
                        .IsRequired()
                        .HasConstraintName("FK__Propertie__Tenan__6A30C649");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("NovaStay.Infrastructure.Models.PropertyService", b =>
                {
                    b.HasOne("NovaStay.Infrastructure.Models.Property", "Property")
                        .WithMany("PropertyServices")
                        .HasForeignKey("PropertyId")
                        .IsRequired()
                        .HasConstraintName("FK_PropertyServices_Properties_PropertyId");

                    b.Navigation("Property");
                });

            modelBuilder.Entity("NovaStay.Infrastructure.Models.Resident", b =>
                {
                    b.HasOne("NovaStay.Infrastructure.Models.Account", "Account")
                        .WithMany("Residents")
                        .HasForeignKey("AccountId")
                        .IsRequired()
                        .HasConstraintName("FK_Residents_Accounts_AccountId");

                    b.Navigation("Account");
                });

            modelBuilder.Entity("NovaStay.Infrastructure.Models.ResidentMembership", b =>
                {
                    b.HasOne("NovaStay.Infrastructure.Models.Account", "Account")
                        .WithMany("ResidentMemberships")
                        .HasForeignKey("AccountId")
                        .IsRequired()
                        .HasConstraintName("FK_ResidentMemberships_Accounts_AccountId");

                    b.HasOne("NovaStay.Infrastructure.Models.Organization", "Organization")
                        .WithMany("ResidentMemberships")
                        .HasForeignKey("OrganizationId")
                        .IsRequired()
                        .HasConstraintName("FK_ResidentMemberships_Organizations_OrganizationId");

                    b.HasOne("NovaStay.Infrastructure.Models.Resident", "Resident")
                        .WithMany("ResidentMemberships")
                        .HasForeignKey("ResidentId")
                        .IsRequired()
                        .HasConstraintName("FK_ResidentMemberships_Residents_ResidentId");

                    b.Navigation("Account");

                    b.Navigation("Organization");

                    b.Navigation("Resident");
                });

            modelBuilder.Entity("NovaStay.Infrastructure.Models.Role", b =>
                {
                    b.HasOne("NovaStay.Infrastructure.Models.Organization", "Organization")
                        .WithMany("Roles")
                        .HasForeignKey("OrganizationId")
                        .IsRequired()
                        .HasConstraintName("FK__Roles__OrganizationId__5BE2A6F2");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("NovaStay.Infrastructure.Models.Room", b =>
                {
                    b.HasOne("NovaStay.Infrastructure.Models.Property", "Property")
                        .WithMany("Rooms")
                        .HasForeignKey("PropertyId")
                        .IsRequired()
                        .HasConstraintName("FK__Rooms__PropertyI__72C60C4A");

                    b.Navigation("Property");
                });

            modelBuilder.Entity("NovaStay.Infrastructure.Models.RoomAvailability", b =>
                {
                    b.HasOne("NovaStay.Infrastructure.Models.Room", "Room")
                        .WithMany("RoomAvailabilities")
                        .HasForeignKey("RoomId")
                        .IsRequired()
                        .HasConstraintName("FK__RoomAvail__RoomI__7E37BEF6");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("NovaStay.Infrastructure.Models.RoomImage", b =>
                {
                    b.HasOne("NovaStay.Infrastructure.Models.Room", "Room")
                        .WithMany("RoomImages")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__RoomImage__RoomI__778AC167");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("NovaStay.Infrastructure.Models.RoomService", b =>
                {
                    b.HasOne("NovaStay.Infrastructure.Models.PropertyService", "PropertyService")
                        .WithMany("RoomServices")
                        .HasForeignKey("PropertyServiceId")
                        .IsRequired()
                        .HasConstraintName("FK_RoomServices_PropertyServices_PropertyServiceId");

                    b.HasOne("NovaStay.Infrastructure.Models.Room", "Room")
                        .WithMany("RoomServices")
                        .HasForeignKey("RoomId")
                        .IsRequired()
                        .HasConstraintName("FK_RoomServices_Rooms_RoomId");

                    b.Navigation("PropertyService");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("NovaStay.Infrastructure.Models.StaffUser", b =>
                {
                    b.HasOne("NovaStay.Infrastructure.Models.Account", "Account")
                        .WithMany("StaffUsers")
                        .HasForeignKey("AccountId")
                        .IsRequired()
                        .HasConstraintName("FK_StaffUsers_Accounts_AccountId");

                    b.HasOne("NovaStay.Infrastructure.Models.Organization", "Organization")
                        .WithMany("StaffUsers")
                        .HasForeignKey("OrganizationId")
                        .IsRequired()
                        .HasConstraintName("FK__Users__OrganizationId__5812160E");

                    b.Navigation("Account");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("NovaStay.Infrastructure.Models.Technician", b =>
                {
                    b.HasOne("NovaStay.Infrastructure.Models.Organization", "Organization")
                        .WithMany("Technicians")
                        .HasForeignKey("OrganizationId")
                        .IsRequired()
                        .HasConstraintName("FK__Technicia__Tenan__3D2915A8");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("RolePermission", b =>
                {
                    b.HasOne("NovaStay.Infrastructure.Models.Permission", null)
                        .WithMany()
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__RolePermi__Permi__628FA481");

                    b.HasOne("NovaStay.Infrastructure.Models.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__RolePermi__RoleI__619B8048");
                });

            modelBuilder.Entity("StaffUserPropertyMapping", b =>
                {
                    b.HasOne("NovaStay.Infrastructure.Models.Property", null)
                        .WithMany()
                        .HasForeignKey("PropertyId")
                        .IsRequired()
                        .HasConstraintName("FK__UserPrope__Prope__6E01572D");

                    b.HasOne("NovaStay.Infrastructure.Models.StaffUser", null)
                        .WithMany()
                        .HasForeignKey("StaffUserId")
                        .IsRequired()
                        .HasConstraintName("FK__UserPrope__UserI__6D0D32F4");
                });

            modelBuilder.Entity("StaffUserRole", b =>
                {
                    b.HasOne("NovaStay.Infrastructure.Models.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__StaffUserRoles__RoleI__66603565");

                    b.HasOne("NovaStay.Infrastructure.Models.StaffUser", null)
                        .WithMany()
                        .HasForeignKey("StaffUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__StaffUserRoles__UserI__656C112C");
                });

            modelBuilder.Entity("NovaStay.Infrastructure.Models.Account", b =>
                {
                    b.Navigation("AccountRefreshTokens");

                    b.Navigation("OwnedOrganizations");

                    b.Navigation("ResidentMemberships");

                    b.Navigation("Residents");

                    b.Navigation("StaffUsers");
                });

            modelBuilder.Entity("NovaStay.Infrastructure.Models.Asset", b =>
                {
                    b.Navigation("AssetAssignments");
                });

            modelBuilder.Entity("NovaStay.Infrastructure.Models.AssetAssignment", b =>
                {
                    b.Navigation("MaintenanceTickets");
                });

            modelBuilder.Entity("NovaStay.Infrastructure.Models.Booking", b =>
                {
                    b.Navigation("Contracts");

                    b.Navigation("Invoices");
                });

            modelBuilder.Entity("NovaStay.Infrastructure.Models.Broker", b =>
                {
                    b.Navigation("Contracts");
                });

            modelBuilder.Entity("NovaStay.Infrastructure.Models.Contract", b =>
                {
                    b.Navigation("Invoices");
                });

            modelBuilder.Entity("NovaStay.Infrastructure.Models.Organization", b =>
                {
                    b.Navigation("AssetAssignments");

                    b.Navigation("Assets");

                    b.Navigation("Bookings");

                    b.Navigation("Brokers");

                    b.Navigation("Contracts");

                    b.Navigation("Invoices");

                    b.Navigation("MaintenanceTickets");

                    b.Navigation("Properties");

                    b.Navigation("ResidentMemberships");

                    b.Navigation("Roles");

                    b.Navigation("StaffUsers");

                    b.Navigation("Technicians");
                });

            modelBuilder.Entity("NovaStay.Infrastructure.Models.Property", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("Contracts");

                    b.Navigation("PropertyServices");

                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("NovaStay.Infrastructure.Models.PropertyService", b =>
                {
                    b.Navigation("RoomServices");
                });

            modelBuilder.Entity("NovaStay.Infrastructure.Models.Resident", b =>
                {
                    b.Navigation("Contracts");

                    b.Navigation("MaintenanceTickets");

                    b.Navigation("ResidentMemberships");
                });

            modelBuilder.Entity("NovaStay.Infrastructure.Models.Room", b =>
                {
                    b.Navigation("AssetAssignments");

                    b.Navigation("Bookings");

                    b.Navigation("Contracts");

                    b.Navigation("MaintenanceTickets");

                    b.Navigation("RoomAvailabilities");

                    b.Navigation("RoomImages");

                    b.Navigation("RoomServices");
                });

            modelBuilder.Entity("NovaStay.Infrastructure.Models.SubscriptionPackage", b =>
                {
                    b.Navigation("Organizations");
                });

            modelBuilder.Entity("NovaStay.Infrastructure.Models.Technician", b =>
                {
                    b.Navigation("MaintenanceTickets");
                });
#pragma warning restore 612, 618
        }
    }
}
